language: go

go:
  - 1.9

go_import_path: github.com/GoogleCloudPlatform/container-engine-accelerators

script:
  - make presubmit
  - make test

notifications:
  email:
    on_success: never
    on_failure: never
