language: go
go:
  - '1.12.x'
go_import_path: github.com/GoogleCloudPlatform/container-engine-accelerators

stages:
  - name: test
  - name: release
    if: tag IS present

jobs:
  include:
    - name: 'Unit tests'
      stage: test
      script: make test
    - name: 'Push image to Docker Hub'
      stage: release
      script:
        - DOCKER_PUSH_LATEST=true make docker-push
